# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vjiaoblack/Compsci/Ageron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vjiaoblack/Compsci/Ageron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vjiaoblack/Compsci/Ageron/CMakeFiles /home/vjiaoblack/Compsci/Ageron/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vjiaoblack/Compsci/Ageron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ageron

# Build rule for target.
Ageron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ageron
.PHONY : Ageron

# fast build rule for target.
Ageron/fast:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/build
.PHONY : Ageron/fast

src/Ageron.o: src/Ageron.cpp.o

.PHONY : src/Ageron.o

# target to build an object file
src/Ageron.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Ageron.cpp.o
.PHONY : src/Ageron.cpp.o

src/Ageron.i: src/Ageron.cpp.i

.PHONY : src/Ageron.i

# target to preprocess a source file
src/Ageron.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Ageron.cpp.i
.PHONY : src/Ageron.cpp.i

src/Ageron.s: src/Ageron.cpp.s

.PHONY : src/Ageron.s

# target to generate assembly for a file
src/Ageron.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Ageron.cpp.s
.PHONY : src/Ageron.cpp.s

src/Building.o: src/Building.cpp.o

.PHONY : src/Building.o

# target to build an object file
src/Building.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Building.cpp.o
.PHONY : src/Building.cpp.o

src/Building.i: src/Building.cpp.i

.PHONY : src/Building.i

# target to preprocess a source file
src/Building.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Building.cpp.i
.PHONY : src/Building.cpp.i

src/Building.s: src/Building.cpp.s

.PHONY : src/Building.s

# target to generate assembly for a file
src/Building.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Building.cpp.s
.PHONY : src/Building.cpp.s

src/Data.o: src/Data.cpp.o

.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i

.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s

.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/Formula.o: src/Formula.cpp.o

.PHONY : src/Formula.o

# target to build an object file
src/Formula.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Formula.cpp.o
.PHONY : src/Formula.cpp.o

src/Formula.i: src/Formula.cpp.i

.PHONY : src/Formula.i

# target to preprocess a source file
src/Formula.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Formula.cpp.i
.PHONY : src/Formula.cpp.i

src/Formula.s: src/Formula.cpp.s

.PHONY : src/Formula.s

# target to generate assembly for a file
src/Formula.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Formula.cpp.s
.PHONY : src/Formula.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/KeyHandler.o: src/KeyHandler.cpp.o

.PHONY : src/KeyHandler.o

# target to build an object file
src/KeyHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/KeyHandler.cpp.o
.PHONY : src/KeyHandler.cpp.o

src/KeyHandler.i: src/KeyHandler.cpp.i

.PHONY : src/KeyHandler.i

# target to preprocess a source file
src/KeyHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/KeyHandler.cpp.i
.PHONY : src/KeyHandler.cpp.i

src/KeyHandler.s: src/KeyHandler.cpp.s

.PHONY : src/KeyHandler.s

# target to generate assembly for a file
src/KeyHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/KeyHandler.cpp.s
.PHONY : src/KeyHandler.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Scenery.o: src/Scenery.cpp.o

.PHONY : src/Scenery.o

# target to build an object file
src/Scenery.cpp.o:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Scenery.cpp.o
.PHONY : src/Scenery.cpp.o

src/Scenery.i: src/Scenery.cpp.i

.PHONY : src/Scenery.i

# target to preprocess a source file
src/Scenery.cpp.i:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Scenery.cpp.i
.PHONY : src/Scenery.cpp.i

src/Scenery.s: src/Scenery.cpp.s

.PHONY : src/Scenery.s

# target to generate assembly for a file
src/Scenery.cpp.s:
	$(MAKE) -f CMakeFiles/Ageron.dir/build.make CMakeFiles/Ageron.dir/src/Scenery.cpp.s
.PHONY : src/Scenery.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Ageron"
	@echo "... src/Ageron.o"
	@echo "... src/Ageron.i"
	@echo "... src/Ageron.s"
	@echo "... src/Building.o"
	@echo "... src/Building.i"
	@echo "... src/Building.s"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/Formula.o"
	@echo "... src/Formula.i"
	@echo "... src/Formula.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/KeyHandler.o"
	@echo "... src/KeyHandler.i"
	@echo "... src/KeyHandler.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Scenery.o"
	@echo "... src/Scenery.i"
	@echo "... src/Scenery.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

